# Generated by Django 4.1.7 on 2023-03-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_custom_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
