# Generated by Django 4.1.7 on 2023-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browserbox', '0005_add_worker_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryBrowserBox',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='available',
        ),
        migrations.AddField(
            model_name='browserbox',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('BS', 'Busy'), ('RS', 'Requested to shut down'), ('SH', 'Shutting down'), ('RI', 'Requested to initalize'), ('IN', 'Initializing')], default='RI', max_length=2),
        ),
        migrations.AddIndex(
            model_name='browserbox',
            index=models.Index(models.F('id'), condition=models.Q(('archived__eq', False)), name='active_browser_boxes_idx'),
        ),
    ]
