name: Publish Docker Image

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Run Tests
      run: |
        poetry run python manage.py test

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout@v3
      
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.REGISTRY_ID }}/pesezjunk:hello .
      
      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.REGISTRY_ID }}/pesezjunk:hello
